name: Push to Lokalise  
on: 
# push:
  workflow_dispatch:

jobs:  
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push files to Lokalise
        uses: lokalise/lokalise-push-action@v3.8.1
        with:
          api_token: 0f39cd8d7efadd7bcf83ec8ac48e3e062a32a119
          project_id: 9533556567c0a3d0951660.98914903
          translations_path: |
            g11n/data/src/main/res/values/%LANG_ISO%
          base_lang: en
          file_format: xml
          rambo_mode: true
          use_tag_tracking: true
          additional_params: |
            --use-automations=true
            --replace-modified=true
        #   --indentation=2sp
        #   --language-mapping=[{"original_language_iso":"en_US","custom_language_iso":"en-US"}]




          
