name: Push to Lokalise  
on: push

jobs:  
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push files to Lokalise
        uses: lokalise/lokalise-push-action@v3.6.0
        with:
          api_token: 13faae115611f5d8ab0327b536e17e506b9b7aa2
          project_id: 9533556567c0a3d0951660.98914903
          translations_path: |
            src/main/resources/locales
          base_lang: en
          file_format: properties
          flat_naming: true
          use_tag_tracking: true
          additional_params: |
            --export-empty-as=skip
            --export-sort=first_added
            --replace-breaks=false
            --use-automation=true
            --replace-modified=true
        #   --indentation=2sp
        #   --language-mapping=[{"original_language_iso":"en_US","custom_language_iso":"en-US"}]




          
